aipscm_study/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajaxtest/', include('ajaxtest.urls')),
    path('formtest/', include('formtest.urls')),
]

ajaxtest/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'ajaxtest'
urlpatterns = [
    path('', views.show_page, name='ajax'),
    path('response/', views.respond_to_ajax, name='res')
]

formtest/urls.py
from django.urls import path
from . import views

app_name = 'formtest'
urlpatterns = [
    path('', views.get_name, name='form'),
    path('success', views.get_success, name='success'),
]

formtest/models.py
from django.db import models

# Create your models here.

formtest/forms.py
from django import forms


class ProfileForm(forms.Form):
    name = forms.CharField(max_length=20, label='名前', help_text='英字のみ', widget=forms.TextInput(attrs={
        'placeholder': 'Name',
    }))
    age = forms.IntegerField(min_value=0, max_value=120, label='年齢', help_text='0以上120以下', widget=forms.NumberInput(attrs={
        'placeholder': '0',
    }))

    # city = forms.ModelChoiceField(required=True, label='都市', widget=forms.TextInput(attrs={
    #         'id': 'selectItems',
    #         'name': 'selectItems',
    #         'placeholder': 'Where is your city'}))

    # city = forms.MultipleChoiceField(required=True, choices=c, label="都市", widget=forms.TextInput(attrs={
    #         'id': 'selectItems',
    #         'name': 'selectItems',
    #         'placeholder': 'Where is your city'}))

    STAFF_BUSINESS_TYPES = {
        (1, "Foo"),
        (2, "Bar"),
        (3, "Cat"),
        (4, "Dog")
    }

    city = forms.MultipleChoiceField(required=True, choices=STAFF_BUSINESS_TYPES, label="都市", widget=forms.SelectMultiple(
        attrs={
            'id': 'selectItems',
            'class':'form-control',
            'name': 'selectItems',
            'placeholder': 'Where is your city'})
    )


    def clean_name(self):
        print('pass clean_name')
        name = self.cleaned_data['name']

        isallalpha = True
        for c in name:
            if not c.isalpha():
                isallalpha = False
                break

        if not isallalpha:
            raise forms.ValidationError('英字以外が含まれています。')

        return name

    def clean_age(self):
        """
        ちなみにフィールドの属性 min_value, max_valueで入力範囲を制限できる。
        それらを設定したらこのバリデーションは不要？
        """
        print('pass clean_age')
        age = self.cleaned_data['age']

        if age < 0 or age > 120:
            raise forms.ValidationError('範囲外です。')

        return age

ajaxtest/views.py
from django.shortcuts import render
from django.http import HttpResponse
import json

# Create your views here.


def show_page(request):
    return render(request, 'ajaxtest/ajaxtest.html')

def respond_to_ajax(request):
    try:
        if request.is_ajax():
            if request.method == 'POST':
                data = json.loads(request.body) #request.body is byte
        return HttpResponse(json.dumps(data), content_type="application/json")

    except Exception as e:
        return e

formtest/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from .forms import ProfileForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ProfileForm(request.POST)
        print(id(form))

        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return redirect('formtest:success')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ProfileForm()
        print(id(form))

    print(id(form))
    return render(request, 'formtest/form.html', {'profile_form': form})

def get_success(request):
    return render(request, 'formtest/success.html')

ajaxtest/templates/ajaxtest/ajaxtest.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>

<body id="page-top">

    {% csrf_token %}
    <input id="input">
    <button id="btnAddPtag"> Click here! </button>


    <div id="divShowInput">
        {% for data in datas%}
            <p> data </p>
        {% endfor %}

    </div>
</body>
    <script src="{% static 'js/init.js' %}"></script>
    <script src="{% static 'js/action.js' %}"></script>
</html>

formtest/templates/formtest/form.html
{% load staticfiles %}
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />


{% with profile_form as f %}
<form action="{% url 'formtest:form' %}" method="POST">
    {% csrf_token %}

    {# フィールドに属さない全体的なエラーの参照 #}
    {% if f.errors %}
        <p>{{ f.non_field_errors }}</p>
    {% endif %}

    <div>
        <label>{{ f.name.label }}</label>:
        {{ f.name }}
        <p>{{ f.name.help_text }}</p>
        {# フィールドに属しているエラーの参照 #}
        <p>{{ f.name.errors }}</p>
    </div>
    <div>
        <label>{{ f.age.label }}</label>:
        {{ f.age }}
        <p>{{ f.age.help_text }}</p>
        {# フィールドに属しているエラーの参照 #}
        <p>{{ f.age.errors }}</p>
    </div>
    <div>
        <label>{{ f.city.label }}</label>:
        {{ f.city }}
    </div>
    <input type="submit" value="送信">
</form>
{% endwith %}
    <!-- bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <!-- custom -->
    <script src="{% static 'js/init.js' %}"></script>

formtest/templates/formtest/success.html
<h1>Success</h1>